### ISSUE TITLE
Supply An requirements.txt file

### ISSUE THREAD

**Issue by whopiyush** [b0tdev/PyGame-Flappy-Bird#3]
As name says

**Comment by whopiyush** [comment]
<pre> File &quot;main.py&quot;, line 126
    IMAGES[&apos;numbers&apos;] = (pygame.image.load(&apos;0.png&apos;).convert_alpha(), pygame.image.load(&apos;1.png&apos;).convert_alpha(), pygame.image.load(&apos;2.png&apos;).convert_alpha(), pygame.image.load(&apos;3.png&apos;).convert_alpha(), pygame.image.load(&apos;4.png&apos;).convert_alpha(), pygame.image.load(5.png&apos;).convert_alpha(), pygame.image.load(&apos;6.png&apos;).convert_alpha(), pygame.image.load(&apos;7.png&apos;).convert_alpha(), pygame.image.load(&apos;8.png&apos;).convert_alpha(), pygame.image.load(&apos;9.png&apos;).convert_alpha())
                                                                                                                                                                                                                                                                           ^
SyntaxError: invalid syntax
Error in sys.excepthook:
Traceback (most recent call last):
  File &quot;/usr/lib/python3/dist-packages/apport_python_hook.py&quot;, line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File &quot;/usr/lib/python3/dist-packages/apport/__init__.py&quot;, line 5, in &lt;module&gt;
    from apport.report import Report
  File &quot;/usr/lib/python3/dist-packages/apport/report.py&quot;, line 30, in &lt;module&gt;
    import apport.fileutils
  File &quot;/usr/lib/python3/dist-packages/apport/fileutils.py&quot;, line 23, in &lt;module&gt;
    from apport.packaging_impl import impl as packaging
  File &quot;/usr/lib/python3/dist-packages/apport/packaging_impl.py&quot;, line 24, in &lt;module&gt;
    import apt
  File &quot;/usr/lib/python3/dist-packages/apt/__init__.py&quot;, line 23, in &lt;module&gt;
    import apt_pkg
ModuleNotFoundError: No module named &apos;apt_pkg&apos;

Original exception was:
  File &quot;main.py&quot;, line 126
    IMAGES[&apos;numbers&apos;] = (pygame.image.load(&apos;0.png&apos;).convert_alpha(), pygame.image.load(&apos;1.png&apos;).convert_alpha(), pygame.image.load(&apos;2.png&apos;).convert_alpha(), pygame.image.load(&apos;3.png&apos;).convert_alpha(), pygame.image.load(&apos;4.png&apos;).convert_alpha(), pygame.image.load(5.png&apos;).convert_alpha(), pygame.image.load(&apos;6.png&apos;).convert_alpha(), pygame.image.load(&apos;7.png&apos;).convert_alpha(), pygame.image.load(&apos;8.png&apos;).convert_alpha(), pygame.image.load(&apos;9.png&apos;).convert_alpha())
                                                                                                                                                                                                                                                                           ^
SyntaxError: invalid syntax
</pre>

**Comment by b0tdev** [comment]
**Hey Piyush Thanks Your Issue Solved see [requirement.txt](https://github.com/b0tdev/PyGame-Flappy-Bird/blob/master/requirements.txt)**

**Comment by whopiyush** [comment]
:)
