### ISSUE TITLE
Let's chat on discord

### ISSUE THREAD

**Issue by whopiyush** [b0tdev/PyGame-Flappy-Bird#7]
I tried to ask you for adding me on Discord - `Piyush#4332`, but it seems you didn't saw those comments, so can u add me or join my server so that we can discuss things there (if any) 
Link ~> https://discord.gg/hWbb4Ee

**Comment by b0tdev** [comment]
Ok

**Comment by b0tdev** [comment]
Can you be our Collaborator

**Comment by b0tdev** [comment]
Can You be our colloborator

**Comment by whopiyush** [comment]
Let's talk on discord

**Comment by PrabaRock7** [comment]
@b0tdev hey hi
